Added testing of the program to the lj script, replaced the scary Java.Applications error with a warning, and updated the README.

diff --git a/lj b/lj
--- a/lj
+++ b/lj
@@ -49,8 +49,29 @@ fi
 
 args="${args} -Ptestfile=${1}"
 "$GRADLE_WRAPPER" $args
-base=$(basename $1)
-upbase="$(tr '[:lower:]' '[:upper:]' <<< ${base:0:1})${base:1}"
-name="LJ${upbase%.*}"
-java -cp generated $name 
-exit
+
+# If the less-java file contains the string "main()", attempt to run it.
+# Otherwise, release a warning and continue
+count=$(grep -c "main()" "$1")
+if [ "$count" -gt "0" ];
+then
+    java -cp generated Main
+else
+    echo "Warning: This program does not contain a main() function and will not be run"
+fi
+
+# --class-path allows specifying where JUnit should look for tests
+# --include-classname allows the name to be anything
+# --disable-banner disables the banner asking contributing to JUnit
+# --scan-class-path checks the full classpath for tests
+# Get the output but do not print it yet
+test_output="$(java -jar libs/junit-platform-console-standalone-1.4.2.jar --class-path ".:generated" --include-classname='.*' --disable-banner --scan-class-path)"
+# Preserve  the exit code of the tests
+test_status="$?"
+
+# The grep -v filter removes lines that are unnecessary or potentially
+#    confusing to an end user.
+echo "$test_output" | grep -v -e '\[.*containers.*\]' -e 'JUnit Vintage' -e 'Test run finished after'
+
+# Ensure the exit code from the tests is the exit code of the script
+exit "$test_status"
